#!/bin/bash

echo "🍺 Barupasas Mobile - Git Workflow Sistema"
echo "=============================================="
echo ""

echo "📱 KAS YRA SUKURTA:"
echo "✅ Mac build konfigūracija (3-5x greičiau)"
echo "✅ Xcode build scriptas (5-10x greičiau)"
echo "✅ Git workflow scriptai"
echo "✅ Automatinis sync sistema"
echo ""

echo "🚀 KAIP NAUDOTI:"
echo ""

echo "1️⃣  PIRMĄ KARTĄ SERVERYJE:"
echo "   ./scripts/setup-git.sh"
echo ""

echo "2️⃣  PIRMĄ KARTĄ MAC ĮRENGINYJE:"
echo "   git clone <your-repo-url> barupasas-mobile"
echo "   cd barupasas-mobile"
echo "   npm install"
echo "   chmod +x scripts/*.sh"
echo ""

echo "3️⃣  KAS KARTĄ KAI DAROTE PAIKEITIMUS:"
echo "   SERVERYJE: ./scripts/git-push.sh"
echo "   MAC: ./scripts/git-pull.sh"
echo ""

echo "4️⃣  BUILD MAC ĮRENGINYJE:"
echo "   ./scripts/build-mac.sh    # EAS build (rekomenduojama)"
echo "   ./scripts/build-xcode.sh  # Xcode build (greičiausias)"
echo ""

echo "5️⃣  AUTOMATINIS SYNC (MAC):"
echo "   ./scripts/git-sync.sh"
echo ""

echo "📋 SCRIPTŲ SĄRAŠAS:"
echo "   setup-git.sh    - Nustato Git (1x serveryje)"
echo "   git-push.sh     - Push pakeitimų (serveryje)"
echo "   git-pull.sh     - Pull pakeitimų (Mac)"
echo "   git-sync.sh     - Automatinis sync (Mac)"
echo "   build-mac.sh    - Mac build (Mac)"
echo "   build-xcode.sh  - Xcode build (Mac)"
echo ""
echo "🔧 PERMISSIONS SPRENDIMAI:"
echo "   quick-fix.sh           - Greitas sprendimas (rekomenduojama)"
echo "   install-mac-tools.sh   - Homebrew sprendimas"
echo "   fix-mac-permissions.sh - Manual fix"
echo ""
echo "🔧 GIT PROBLEMŲ SPRENDIMAI:"
echo "   auto-fix-git.sh        - Automatinis Git fix (rekomenduojama)"
echo "   fix-git-issues.sh      - Manual Git fix"
echo ""
echo "🔧 MAC GIT KONFLIKTŲ SPRENDIMAI:"
echo "   force-pull-mac.sh      - Force pull (rekomenduojama)"
echo "   fix-mac-git-conflicts.sh - Saugus sprendimas"
echo ""
echo "🔧 DEPENDENCIES SPRENDIMAI:"
echo "   fix-dependencies.sh    - Dependencies fix (rekomenduojama)"
echo "   build-expo-go.sh      - Expo Go build (greičiausias)"
echo ""
echo "🔧 EXPO START SPRENDIMAI:"
echo "   fix-version-mismatch.sh - Versijų nesutapimas (rekomenduojama)"
echo "   fix-port-issues.sh      - Portų problemos"
echo "   fix-macos-permissions.sh - macOS permissions"
echo "   start-expo-simple.sh     - Expo start (be problemų)"
echo ""
echo "🔧 PRISIJUNGIMO SPRENDIMAI:"
echo "   fix-connection-issues.sh - Prisijungimo problemos (rekomenduojama)"
echo "   start-expo-tunnel.sh     - Tunnel start (be problemų)"
echo "   start-expo-local.sh      - Local network start"
echo "   start-expo-manual.sh     - Manual start"
echo ""

echo "⚡ GREIČIO POBŪDIS:"
echo "   Cloud build: 15-30 min"
echo "   Mac build:   3-8 min (3-5x greičiau)"
echo "   Xcode build: 2-5 min (5-10x greičiau)"
echo ""

echo "📚 DAUGIAU INFORMACIJOS:"
echo "   README.md         - Pagrindinės instrukcijos"
echo "   BUILD-MAC.md      - Mac build instrukcijos"
echo "   GIT-WORKFLOW.md   - Git workflow instrukcijos"
echo ""

echo "🎯 REZULTATAS:"
echo "   Kodas automatiškai perkeliamas iš serverio į Mac"
echo "   Buildai daug greičiau nei cloud"
echo "   Automatinis sync ir dependency management"
echo ""

echo "💡 PATARIMAS:"
echo "   Visada naudokite scriptus - jie automatiškai daro viską!"
echo "   Mac build yra daug greičiau nei cloud build!"
echo ""
